CREATE OR REPLACE TYPE "PLAYGROUND"."ITEM" 
  AUTHID DEFINER
  AS
  OBJECT (N_WEIGHT NUMBER(19, 2), --weight in kg
          N_VALUE NUMBER(19, 2), --value in $
          MEMBER FUNCTION GET_WEIGHT
            RETURN NUMBER,
          MEMBER FUNCTION GET_VALUE
            RETURN NUMBER);
/
CREATE OR REPLACE TYPE BODY "PLAYGROUND"."ITEM" 
  AS

    MEMBER FUNCTION GET_WEIGHT
      RETURN NUMBER
      IS
      BEGIN
        RETURN SELF.N_WEIGHT;
      END GET_WEIGHT;

    MEMBER FUNCTION GET_VALUE
      RETURN NUMBER
      IS
      BEGIN
        RETURN SELF.N_VALUE;
      END GET_VALUE;

  END;
/
