CREATE OR REPLACE TYPE "PLAYGROUND"."ITEM_ASSORTMENT_CONTAINER" 
  AUTHID DEFINER
  AS
  OBJECT (ASSORTMENTS PLAYGROUND.ITEM_ASSORTMENTS,
          CONSTRUCTOR FUNCTION ITEM_ASSORTMENT_CONTAINER(SELF IN OUT ITEM_ASSORTMENT_CONTAINER)
            RETURN SELF AS RESULT,
          MEMBER PROCEDURE ADD_ASSORTMENT(SELF IN OUT NOCOPY ITEM_ASSORTMENT_CONTAINER,
                                          ASSORTMENT         PLAYGROUND.ITEM_ASSORTMENT),
          MEMBER FUNCTION GET_TOTAL_ASSORTMENTS
            RETURN NUMBER,
          MEMBER FUNCTION GET_ASSRTMNTS_WITH_WGHT_BELOW(P_N_WEIGHT NUMBER)
            RETURN PLAYGROUND.ITEM_ASSORTMENTS);
/
CREATE OR REPLACE TYPE BODY "PLAYGROUND"."ITEM_ASSORTMENT_CONTAINER" 
  AS

    CONSTRUCTOR FUNCTION ITEM_ASSORTMENT_CONTAINER(SELF IN OUT ITEM_ASSORTMENT_CONTAINER)
      RETURN SELF AS RESULT
      IS
      BEGIN
        SELF.ASSORTMENTS := PLAYGROUND.ITEM_ASSORTMENTS();
        RETURN;
      END;

    MEMBER PROCEDURE ADD_ASSORTMENT(SELF IN OUT NOCOPY ITEM_ASSORTMENT_CONTAINER,
                                    ASSORTMENT         PLAYGROUND.ITEM_ASSORTMENT)
      IS
      BEGIN
        SELF.ASSORTMENTS.extend;
        SELF.ASSORTMENTS(SELF.ASSORTMENTS.last) := ASSORTMENT;
      END ADD_ASSORTMENT;

    MEMBER FUNCTION GET_TOTAL_ASSORTMENTS
      RETURN NUMBER
      IS
      BEGIN
        RETURN SELF.ASSORTMENTS.count;
      END GET_TOTAL_ASSORTMENTS;

    MEMBER FUNCTION GET_ASSRTMNTS_WITH_WGHT_BELOW(P_N_WEIGHT NUMBER)
      RETURN PLAYGROUND.ITEM_ASSORTMENTS
      IS
        CURRENT_ASSORTMENT PLAYGROUND.ITEM_ASSORTMENT;
        R_RES              PLAYGROUND.ITEM_ASSORTMENTS := PLAYGROUND.ITEM_ASSORTMENTS();
      BEGIN
        FOR IDX IN SELF.ASSORTMENTS.first .. SELF.ASSORTMENTS.last
        LOOP
          CURRENT_ASSORTMENT := SELF.ASSORTMENTS(IDX);
          IF CURRENT_ASSORTMENT.GET_TOTAL_WEIGHT() <= P_N_WEIGHT
          THEN
            R_RES.extend;
            R_RES(R_RES.last) := CURRENT_ASSORTMENT;
          END IF;
        END LOOP;
        RETURN R_RES;
      END GET_ASSRTMNTS_WITH_WGHT_BELOW;

  END;
/
