CREATE OR REPLACE TYPE "PLAYGROUND"."SHIT" AUTHID DEFINER
  AS
  OBJECT (SOME_TEXT NVARCHAR2(100),
          SOME_OTHER_TEXT NVARCHAR2(100),
          MEMBER PROCEDURE SET_SOME_TEXT(SELF IN OUT NOCOPY SHIT,
                                         NEW_TEXT           VARCHAR2),
          CONSTRUCTOR FUNCTION SHIT(P_TEXT NVARCHAR2)
            RETURN SELF AS RESULT);
/
CREATE OR REPLACE TYPE BODY "PLAYGROUND"."SHIT" 
  AS

    CONSTRUCTOR FUNCTION SHIT(P_TEXT NVARCHAR2)
      RETURN SELF AS RESULT
      AS
      BEGIN
        SELF.SOME_TEXT := P_TEXT;
        RETURN;
      END;

    MEMBER PROCEDURE SET_SOME_TEXT(SELF IN OUT NOCOPY SHIT,
                                   NEW_TEXT           VARCHAR2)
      AS
      BEGIN
        SELF.SOME_TEXT := NEW_TEXT;
      END SET_SOME_TEXT;

  END;
/
