CREATE OR REPLACE PACKAGE BODY "PLAYGROUND"."TEST_ASSORTMENT_SHIT" 
  AS


  PROCEDURE TEST_CREATE_ITEM
    AS
      N_WEIGHT  NUMBER(19) := 10;
      N_VALUE   NUMBER(19) := 5;
      TEST_ITEM PLAYGROUND.ITEM;
    BEGIN
      DBMS_OUTPUT.PUT_LINE('test creation of ITEM');
      TEST_ITEM := NEW PLAYGROUND.ITEM(N_WEIGHT, N_VALUE);

      UT.EXPECT(TEST_ITEM.GET_WEIGHT()).to_equal(N_WEIGHT);
      UT.EXPECT(TEST_ITEM.GET_VALUE()).to_equal(N_VALUE);

    END TEST_CREATE_ITEM;

  PROCEDURE TEST_ITEM_ASSORTMENT
    AS
      N_WEIGHT_1           NUMBER(19)       := 10;
      N_VALUE_1            NUMBER(19)       := 5;
      N_WEIGHT_2           NUMBER(19)       := 15;
      N_VALUE_2            NUMBER(19)       := 10;
      TEST_ITEMS           PLAYGROUND.ITEMS := PLAYGROUND.ITEMS(NEW PLAYGROUND.ITEM(N_WEIGHT_1, N_VALUE_1), NEW PLAYGROUND.ITEM(N_WEIGHT_2, N_VALUE_2));

      TEST_ITEM_ASSORTMENT PLAYGROUND.ITEM_ASSORTMENT;
    BEGIN
      DBMS_OUTPUT.PUT_LINE('test creation of ITEM_ASSORTMENT');
      TEST_ITEM_ASSORTMENT := NEW PLAYGROUND.ITEM_ASSORTMENT(TEST_ITEMS);

      UT.EXPECT(TEST_ITEM_ASSORTMENT.GET_TOTAL_WEIGHT()).to_equal(N_WEIGHT_1 + N_WEIGHT_2);
      UT.EXPECT(TEST_ITEM_ASSORTMENT.GET_TOTAL_VALUE()).to_equal(N_VALUE_1 + N_VALUE_2);

    END TEST_ITEM_ASSORTMENT;


  PROCEDURE TEST_ITEM_ASSORTMENT_CONTAINER
    AS
      TEST_ITEMS_1                   PLAYGROUND.ITEMS           := PLAYGROUND.ITEMS(NEW PLAYGROUND.ITEM(10, 10), NEW PLAYGROUND.ITEM(20, 20));
      TEST_ITEMS_2                   PLAYGROUND.ITEMS           := PLAYGROUND.ITEMS(NEW PLAYGROUND.ITEM(40, 40));
      TEST_ITEMS_3                   PLAYGROUND.ITEMS           := PLAYGROUND.ITEMS(NEW PLAYGROUND.ITEM(40, 40), NEW PLAYGROUND.ITEM(20, 40));
      TEST_ASSORTMENT_1              PLAYGROUND.ITEM_ASSORTMENT := NEW PLAYGROUND.ITEM_ASSORTMENT(TEST_ITEMS_1);
      TEST_ASSORTMENT_2              PLAYGROUND.ITEM_ASSORTMENT := NEW PLAYGROUND.ITEM_ASSORTMENT(TEST_ITEMS_2);
      TEST_ASSORTMENT_3              PLAYGROUND.ITEM_ASSORTMENT := NEW PLAYGROUND.ITEM_ASSORTMENT(TEST_ITEMS_3);

      ASSORTMENT_CONTAINER           PLAYGROUND.ITEM_ASSORTMENT_CONTAINER;
      ASSRTMNTS_TOTL_WGHT_BLOW_THRES PLAYGROUND.ITEM_ASSORTMENTS;
    BEGIN
      DBMS_OUTPUT.PUT_LINE('test creation of ITEM_ASSORTMENT_CONTAINER');
      ASSORTMENT_CONTAINER := PLAYGROUND.ITEM_ASSORTMENT_CONTAINER();
      DBMS_OUTPUT.PUT_LINE('assortment-container successfully created');

      ASSORTMENT_CONTAINER.ADD_ASSORTMENT(TEST_ASSORTMENT_1);
      ASSORTMENT_CONTAINER.ADD_ASSORTMENT(TEST_ASSORTMENT_2);
      ASSORTMENT_CONTAINER.ADD_ASSORTMENT(TEST_ASSORTMENT_3);

      UT.EXPECT(ASSORTMENT_CONTAINER.GET_TOTAL_ASSORTMENTS()).to_equal(3);

      ASSRTMNTS_TOTL_WGHT_BLOW_THRES := ASSORTMENT_CONTAINER.GET_ASSRTMNTS_WITH_WGHT_BELOW(50);
      UT.EXPECT(ASSRTMNTS_TOTL_WGHT_BLOW_THRES.count).to_equal(2);

      ASSRTMNTS_TOTL_WGHT_BLOW_THRES := ASSORTMENT_CONTAINER.GET_ASSRTMNTS_WITH_WGHT_BELOW(60);
      UT.EXPECT(ASSRTMNTS_TOTL_WGHT_BLOW_THRES.count).to_equal(3);

    END TEST_ITEM_ASSORTMENT_CONTAINER;

END TEST_ASSORTMENT_SHIT;
/
