CREATE OR REPLACE PACKAGE BODY "PLAYGROUND"."TEST_LIST_UTILS" 
  AS


  PROCEDURE CREATE_INTEGER_ARRAY_FROM_TO
    AS
      N_START   NUMBER(19)    := 1;
      N_STOP    NUMBER(19)    := 5;

      R_RES     PLAYGROUND.INTEGER_ARRAY;
      V_RES_STR NVARCHAR2(10) := '';
    BEGIN
      R_RES := LIST_UTILS.CREATE_INTEGER_ARRAY_FROM_TO(N_START, N_STOP);

      FOR IDX IN R_RES.first .. R_RES.last
      LOOP
        V_RES_STR := CONCAT(V_RES_STR, R_RES(IDX));
      END LOOP;

      UT.EXPECT(V_RES_STR).TO_EQUAL('12345');

    END CREATE_INTEGER_ARRAY_FROM_TO;


END TEST_LIST_UTILS;
/
