CREATE OR REPLACE PACKAGE "PLAYGROUND"."LIST_UTILS" AUTHID DEFINER
  AS


  FUNCTION COPY_ARRAY(R_INPUT_ARRAY IN INTEGER_ARRAY)
    RETURN INTEGER_ARRAY;

  PROCEDURE INITIALIZE_LIST(INIT_LIST IN OUT NOCOPY INTEGER_ARRAY,
                            INITSIZE  IN            NUMBER);

  FUNCTION CREATE_INTEGER_ARRAY_FROM_TO(P_N_START IN NUMBER,
                                        P_N_END   IN NUMBER)
    RETURN INTEGER_ARRAY;

  FUNCTION CREATE_EMPTY_INTEGER_MATRIX(NUMBER_OF_ROWS    NUMBER,
                                       NUMBER_OF_COLUMNS NUMBER)
    RETURN PLAYGROUND.INTEGER_MATRIX;



END LIST_UTILS;
/
