DROP TYPE TEST_IT FORCE;

CREATE TYPE TEST_IT
  AUTHID DEFINER
  AS
  OBJECT (MEMBER_VAR VARCHAR2(10),
          MEMBER FUNCTION MODIFY_MEMBER_VARIABLE(SELF IN OUT TEST_IT,
                                                 NEW_VALUE   VARCHAR2)
            RETURN NUMBER);
/

CREATE TYPE BODY TEST_IT
  AS

    MEMBER FUNCTION MODIFY_MEMBER_VARIABLE(SELF IN OUT TEST_IT,
                                           NEW_VALUE   VARCHAR2)
      RETURN NUMBER
      IS
      BEGIN
        SELF.MEMBER_VAR := NEW_VALUE;
        RETURN 0;
      END MODIFY_MEMBER_VARIABLE;

  END;
/

